version: "3.9"

services:
  postgres:
    container_name: teebay-postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=teebay
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: teebay-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 4000:4000
    depends_on:
      - postgres

volumes:
  postgres_data:
