version: "3.9"

services:
  api:
    container_name: teebay-api
    build:
      context: ./api
      args:
        NODE_ENV: production
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    command: pnpm start:prod
