version: "3.9"

services:
  api:
    container_name: teebay-api
    build:
      context: ./api
      args:
        NODE_ENV: development
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./api/:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
    command: pnpm dev
